import { getFontEmbedCSS, toPng } from "html-to-image";
import type { FormatDef } from "@/lib/pass/formats";
import { settleAnimations } from "./motion";
import { EVENT } from "@/lib/config/event";

/*
  Getting the pass off the page.

  Two ways out: the OS share sheet where it exists, a download everywhere
  else. Direct posting to X, Instagram or LinkedIn was tried and removed —
  none of them accept an image through a URL intent, so it would need OAuth
  and a server holding tokens. navigator.share() hands the real PNG to the
  platform's own app instead, which is the same outcome without any of that.
*/

const SHARE_TITLE = EVENT.fullName;
const SHARE_TEXT = `I'm going to ${EVENT.fullName}. See you in ${EVENT.city}.`;

/*
  html-to-image inlines every @font-face it can find, and the dashboard
  declares six families — Red Hat Display alone is seven weights in two
  styles. Resolving that on every export means base64ing ~30 woff2 files each
  time. Computed once and reused, so only the first export pays for it.

  Passing `fontEmbedCSS` to toPng makes it skip its own resolution entirely.
*/
let embedCSS: Promise<string> | null = null;

function passFontEmbedCSS(node: HTMLElement): Promise<string> {
  embedCSS ??= getFontEmbedCSS(node, { preferredFontFormat: "woff2" }).catch(
    (err) => {
      // A failure here is recoverable — toPng falls back to its own
      // resolution — but it must not poison the cache for later exports.
      console.error("[pass] font embed CSS failed:", err);
      embedCSS = null;
      return "";
    },
  );
  return embedCSS;
}

/*
  document.fonts.ready only awaits loads already in flight, and CSS @font-face
  are lazy: switch typeface and hit export in the same beat and the new face
  may not have started loading, so the pass rasterizes in the old one.

  The family names are generated by next/font ('__Space_Grotesk_a1b2c3'), so
  they can't be hardcoded — this reads back what the frame actually computed
  to and asks for exactly those.
*/
async function loadUsedFaces(node: HTMLElement): Promise<void> {
  const specs = new Map<string, string>();

  for (const el of node.querySelectorAll<HTMLElement>("*")) {
    const cs = getComputedStyle(el);
    const spec = `${cs.fontStyle} ${cs.fontWeight} ${cs.fontSize} ${cs.fontFamily}`;
    // The text matters: fonts.load() only guarantees the glyphs it is asked
    // for. 'M' is the fallback for elements that render an image or a border.
    if (!specs.has(spec)) specs.set(spec, el.textContent?.slice(0, 64) || "M");
  }

  await Promise.all(
    Array.from(specs, ([spec, text]) =>
      document.fonts.load(spec, text).catch(() => {}),
    ),
  );
  await document.fonts.ready;
}

/** Rasterizes the frame at the format's exact pixel size. */
export async function renderFrame(
  node: HTMLElement,
  format: FormatDef,
): Promise<Blob> {
  await loadUsedFaces(node);
  const fontEmbedCSS = await passFontEmbedCSS(node);

  // After the awaits above, React may have flushed a format-flip midpoint swap
  // if settle ran too early — settle immediately before capture so the DOM
  // still matches the `format` dimensions passed in, and half-faded backdrops
  // are not rasterized either.
  settleAnimations();

  node.setAttribute("data-printing", "");
  let dataUrl: string;
  try {
    dataUrl = await toPng(node, {
      pixelRatio: 1,
      width: format.width,
      height: format.height,
      fontEmbedCSS,
      // Deliberately no cacheBust. It was there for the static-export build,
      // where the backdrops were fetched cross-origin; here every asset is
      // same-origin, and busting the cache re-downloads and re-base64s a
      // multi-hundred-KB JPEG on every single export — which the share path
      // below cannot afford.
    });
  } finally {
    node.removeAttribute("data-printing");
  }

  return (await fetch(dataUrl)).blob();
}

export function fileName(name: string, suffix: string): string {
  const first = name
    .trim()
    .split(/\s+/)[0]
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "");

  return `mhacks-ticket-${first || "pass"}-${suffix}.png`;
}

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  // Give the browser a beat to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

/*
  Whether this browser can share a file at all.

  A one-byte PNG is enough to ask: canShare inspects the MIME type and the
  fact that it is a File, not the bytes. Cached because the answer cannot
  change within a session.

  Must not be read during SSR, and must not decide *rendered* text on the
  first client pass either — put it behind useMounted() or the button's label
  will differ between the server markup and the hydrated one.
*/
let fileShareSupported: boolean | null = null;

export function canShareFiles(): boolean {
  if (fileShareSupported !== null) return fileShareSupported;

  if (
    typeof navigator === "undefined" ||
    !navigator.canShare ||
    !navigator.share
  ) {
    return (fileShareSupported = false);
  }

  try {
    const probe = new File([new Uint8Array(1)], "pass.png", {
      type: "image/png",
    });
    fileShareSupported = navigator.canShare({ files: [probe] });
  } catch {
    fileShareSupported = false;
  }

  return fileShareSupported;
}

export type ShareOutcome = "shared" | "downloaded" | "cancelled";

/**
 * Hands the pass to the OS share sheet, falling back to a download.
 *
 * Must be called from a user gesture: navigator.share() needs transient
 * activation, and rasterizing the frame first spends part of that window —
 * which is why renderFrame drops cacheBust and caches the font embed CSS. A
 * repeat export has to come in well under it.
 *
 * No `url` in the payload: several targets drop the file when a URL is also
 * present, and the image is the whole point.
 */
export async function shareFrame(
  node: HTMLElement,
  name: string,
  format: FormatDef,
): Promise<ShareOutcome> {
  const filename = fileName(name, format.id);
  const blob = await renderFrame(node, format);
  const file = new File([blob], filename, { type: "image/png" });

  if (!canShareFiles() || !navigator.canShare({ files: [file] })) {
    saveBlob(blob, filename);
    return "downloaded";
  }

  try {
    await navigator.share({
      files: [file],
      title: SHARE_TITLE,
      text: SHARE_TEXT,
    });
    return "shared";
  } catch (err) {
    // Dismissing the sheet is not a failure and must not surface as an error:
    // the pass is still on screen and the button is ready to go again.
    if (err instanceof DOMException && err.name === "AbortError") {
      return "cancelled";
    }
    // Anything else — a lapsed gesture, a target that refused the file —
    // still owes the hacker their PNG.
    console.error("[pass] share failed, falling back to download:", err);
    saveBlob(blob, filename);
    return "downloaded";
  }
}

export async function downloadFrame(
  node: HTMLElement,
  name: string,
  format: FormatDef,
): Promise<void> {
  saveBlob(await renderFrame(node, format), fileName(name, format.id));
}
