// Declarative definition of the local-development .env file.
//
// To add a new variable, append an `env(...)` entry to a section below (or add a
// new section). Nothing else needs to change — the generator reads this schema,
// resolves each value from its source, and renders the file.
//
// Values come from one of two sources:
//   • supabaseStatus("KEY") — pulled live from `supabase status -o env`
//   • preserved("fallback") — kept from the existing .env if present, else the
//     fallback (use for app-side config that Supabase doesn't know about)

/** Resolves a variable's value at generation time. */
export type EnvSource =
  | { readonly kind: "supabase"; readonly statusKey: string }
  | { readonly kind: "preserved"; readonly fallback: string };

/** Pull the value from `supabase status -o env` under the given key. */
export const supabaseStatus = (statusKey: string): EnvSource => ({
  kind: "supabase",
  statusKey,
});

/** Keep the existing .env value if present; otherwise use `fallback`. */
export const preserved = (fallback: string): EnvSource => ({
  kind: "preserved",
  fallback,
});

export interface EnvVar {
  readonly name: string;
  readonly source: EnvSource;
  /** Comment block rendered above the variable (multi-line allowed). */
  readonly comment?: string;
}

export interface EnvSection {
  /** Section header comment, e.g. "Supabase Auth (client + SSR)". */
  readonly title: string;
  /** Optional prose under the header (multi-line allowed). */
  readonly description?: string;
  readonly vars: readonly EnvVar[];
}

const REMOTE_MIGRATE_NOTE = `Day-to-day development runs against your LOCAL Supabase database. Start it with
\`pnpm db:local\` (requires Docker), then \`pnpm db:push\`.

To apply migrations to the SHARED REMOTE, do NOT edit this file. Run migrate with
the remote URL inline so it can't happen by accident (the shell value wins):

  DATABASE_URL="postgresql://postgres.[REF]:[PW]@aws-0-[REGION].pooler.supabase.com:6543/postgres" pnpm db:migrate`;

export const schema: readonly EnvSection[] = [
  {
    title: "Database",
    description: REMOTE_MIGRATE_NOTE,
    vars: [{ name: "DATABASE_URL", source: supabaseStatus("DB_URL") }],
  },
  {
    title: "Supabase Auth (client + SSR)",
    description: `For the remote project, copy the URL + publishable key from
Supabase Dashboard -> Project Settings -> API and set them on your hosting platform.`,
    vars: [
      {
        name: "NEXT_PUBLIC_SUPABASE_URL",
        source: supabaseStatus("API_URL"),
      },
      {
        name: "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
        source: supabaseStatus("PUBLISHABLE_KEY"),
      },
    ],
  },
  {
    title: "Auth redirect allow-list",
    description: `Read by supabase/config.toml via env() so the same config works local vs
remote. Pick ONE host and use it everywhere (browser, emails) — localhost and
127.0.0.1 are different cookie origins. Not part of supabase status, so these
are preserved across regeneration.`,
    vars: [
      {
        name: "SUPABASE_AUTH_SITE_URL",
        source: preserved("http://localhost:3000"),
      },
      {
        name: "SUPABASE_AUTH_ADDITIONAL_REDIRECT_URLS",
        source: preserved("http://localhost:3000"),
      },
    ],
  },
];
