CREATE TYPE "public"."application_status" AS ENUM('pending', 'reviewed', 'flagged');--> statement-breakpoint
CREATE TABLE "hacker_applicants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"status" "application_status" DEFAULT 'pending' NOT NULL,
	"age" integer NOT NULL,
	"gender" text NOT NULL,
	"gender_other" text,
	"ethnicity" text NOT NULL,
	"ethnicity_other" text,
	"university" text NOT NULL,
	"university_other" text,
	"country" text NOT NULL,
	"country_other" text,
	"degree" text NOT NULL,
	"degree_other" text,
	"graduation_year" integer NOT NULL,
	"previous_hackathons" integer NOT NULL,
	"major" text NOT NULL,
	"major_other" text,
	"resume" text,
	"why_attend" text NOT NULL,
	"technical_challenge" text NOT NULL,
	"proud_project" text NOT NULL,
	"anything_else" text,
	"transportation_type" text NOT NULL,
	"coming_from" text NOT NULL,
	"shirt_size" text NOT NULL,
	"has_allergies" boolean NOT NULL,
	"allergies_description" text,
	"needs_travel_reimbursement" boolean NOT NULL,
	"would_attend_without_reimbursement" boolean,
	"github" text,
	"linkedin" text,
	"personal_site" text,
	"follows_instagram" boolean,
	"mlh_code_of_conduct" boolean NOT NULL,
	"mlh_privacy_policy" boolean NOT NULL,
	"mlh_emails" boolean NOT NULL,
	"sponsor_emails" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "hacker_applicants_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "judge_applicants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"status" "application_status" DEFAULT 'pending' NOT NULL,
	"age" integer NOT NULL,
	"gender" text NOT NULL,
	"gender_other" text,
	"ethnicity" text NOT NULL,
	"ethnicity_other" text,
	"university" text NOT NULL,
	"university_other" text,
	"country" text NOT NULL,
	"country_other" text,
	"degree" text NOT NULL,
	"degree_other" text,
	"graduation_year" integer NOT NULL,
	"previous_hackathons" integer NOT NULL,
	"major" text NOT NULL,
	"major_other" text,
	"resume" text,
	"why_attend" text NOT NULL,
	"technical_challenge" text NOT NULL,
	"proud_project" text NOT NULL,
	"anything_else" text,
	"transportation_type" text NOT NULL,
	"coming_from" text NOT NULL,
	"shirt_size" text NOT NULL,
	"has_allergies" boolean NOT NULL,
	"allergies_description" text,
	"needs_travel_reimbursement" boolean NOT NULL,
	"would_attend_without_reimbursement" boolean,
	"github" text,
	"linkedin" text,
	"personal_site" text,
	"follows_instagram" boolean,
	"mlh_code_of_conduct" boolean NOT NULL,
	"mlh_privacy_policy" boolean NOT NULL,
	"mlh_emails" boolean NOT NULL,
	"sponsor_emails" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "judge_applicants_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "hacker_applicants" ADD CONSTRAINT "hacker_applicants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "judge_applicants" ADD CONSTRAINT "judge_applicants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;