export const ethnicityOptions = [
  { value: "american-indian", label: "American Indian or Alaska Native" },
  { value: "asian", label: "Asian" },
  { value: "black", label: "Black or African American" },
  { value: "hispanic", label: "Hispanic or Latino / Latina / Latinx" },
  { value: "mena", label: "Middle Eastern or North African" },
  { value: "pacific-islander", label: "Native Hawaiian or Pacific Islander" },
  { value: "white", label: "White" },
  { value: "multiracial", label: "Multiracial (please describe)" },
];

export const countries = [
  { value: "us", label: "United States" },
  { value: "canada", label: "Canada" },
  { value: "uk", label: "United Kingdom" },
  { value: "mexico", label: "Mexico" },
  { value: "other", label: "Other" },
];

export const degreeOptions = [
  { value: "high-school", label: "High School / Secondary School" },
  { value: "associates", label: "Associate's" },
  { value: "bachelors", label: "Bachelor's" },
  { value: "masters", label: "Master's" },
  { value: "phd", label: "PhD / Doctorate" },
  { value: "other", label: "Other" },
];

export const majorOptions = [
  // Computing
  { value: "cs", label: "Computer Science" },
  { value: "se", label: "Software Engineering" },
  { value: "ce", label: "Computer Engineering" },
  { value: "ai", label: "Artificial Intelligence / Machine Learning" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "datasci", label: "Data Science" },
  { value: "hci", label: "Human-Computer Interaction" },
  { value: "game-design", label: "Game Design / Game Development" },
  { value: "infosci", label: "Information Science / Information Systems" },
  { value: "mis", label: "Management Information Systems" },
  // Engineering
  { value: "ae", label: "Aerospace Engineering" },
  { value: "biomed", label: "Biomedical Engineering" },
  { value: "chem-eng", label: "Chemical Engineering" },
  { value: "civil", label: "Civil Engineering" },
  { value: "ee", label: "Electrical Engineering" },
  { value: "enviro-eng", label: "Environmental Engineering" },
  { value: "ie", label: "Industrial Engineering" },
  { value: "mech", label: "Mechanical Engineering" },
  { value: "nuke", label: "Nuclear Engineering" },
  { value: "robotics", label: "Robotics" },
  { value: "sys-eng", label: "Systems Engineering" },
  // Sciences
  { value: "applied-math", label: "Applied Mathematics" },
  { value: "biochem", label: "Biochemistry" },
  { value: "biology", label: "Biology" },
  { value: "chem", label: "Chemistry" },
  { value: "cog-sci", label: "Cognitive Science" },
  { value: "enviro-sci", label: "Environmental Science" },
  { value: "math", label: "Mathematics" },
  { value: "neuro", label: "Neuroscience" },
  { value: "physics", label: "Physics" },
  { value: "stats", label: "Statistics" },
  // Business / Social
  { value: "accounting", label: "Accounting" },
  { value: "business", label: "Business Administration" },
  { value: "econ", label: "Economics" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "finance", label: "Finance" },
  { value: "marketing", label: "Marketing" },
  // Design / Arts
  { value: "arch", label: "Architecture" },
  { value: "design", label: "Design (Graphic / UX / Product)" },
  { value: "fine-arts", label: "Fine Arts" },
  // Humanities / Other
  { value: "comm", label: "Communications / Media" },
  { value: "education", label: "Education" },
  { value: "linguistics", label: "Linguistics" },
  { value: "polisci", label: "Political Science" },
  { value: "psych", label: "Psychology" },
  { value: "sociology", label: "Sociology" },
  { value: "other", label: "Other or multiple majors" },
];

export const comingFromOptions = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "Washington, D.C." },
  { value: "international", label: "International" },
];

export const transportationOptions = [
  { value: "driving", label: "Driving" },
  { value: "flying", label: "Flying" },
  { value: "bus", label: "Bus" },
  { value: "train", label: "Train" },
  { value: "local", label: "Local" },
];

export const shirtSizeOptions = [
  { value: "xs", label: "XS" },
  { value: "s", label: "S" },
  { value: "m", label: "M" },
  { value: "l", label: "L" },
  { value: "xl", label: "XL" },
  { value: "xxl", label: "XXL" },
];

export const dietaryOptions = [
  { value: "vegetarian", label: "Vegetarian" },
  { value: "vegan", label: "Vegan" },
  { value: "kosher", label: "Kosher" },
  { value: "gluten-free", label: "Gluten-free" },
  { value: "halal", label: "Halal" },
  { value: "nut-free", label: "Nut-free" },
  { value: "dairy-free", label: "Dairy-free" },
  { value: "other", label: "Other" },
];
