export const ethnicityOptions = [
  { value: "american-indian", label: "American Indian or Alaska Native" },
  { value: "asian", label: "Asian" },
  { value: "black", label: "Black or African American" },
  { value: "hispanic", label: "Hispanic or Latino / Latina / Latinx" },
  { value: "mena", label: "Middle Eastern or North African" },
  { value: "pacific-islander", label: "Native Hawaiian or Pacific Islander" },
  { value: "white", label: "White" },
  { value: "multiracial", label: "Multiracial (please describe)" },
];

export const universities = [
  // Michigan / Midwest
  { value: "umich", label: "University of Michigan" },
  { value: "msu", label: "Michigan State University" },
  { value: "mtu", label: "Michigan Technological University" },
  { value: "uiuc", label: "University of Illinois Urbana-Champaign" },
  { value: "northwestern", label: "Northwestern University" },
  { value: "osu", label: "Ohio State University" },
  { value: "purdue", label: "Purdue University" },
  { value: "iub", label: "Indiana University Bloomington" },
  { value: "umn", label: "University of Minnesota" },
  { value: "wisc", label: "University of Wisconsin-Madison" },
  { value: "iowa-state", label: "Iowa State University" },
  // Top CS / Engineering
  { value: "mit", label: "Massachusetts Institute of Technology" },
  { value: "stanford", label: "Stanford University" },
  { value: "cmu", label: "Carnegie Mellon University" },
  { value: "gatech", label: "Georgia Institute of Technology" },
  { value: "caltech", label: "California Institute of Technology" },
  { value: "cornell", label: "Cornell University" },
  { value: "ucberkeley", label: "University of California, Berkeley" },
  { value: "ucsd", label: "University of California, San Diego" },
  { value: "ucla", label: "University of California, Los Angeles" },
  { value: "uci", label: "University of California, Irvine" },
  { value: "ucsb", label: "University of California, Santa Barbara" },
  { value: "ucdavis", label: "University of California, Davis" },
  { value: "ucsc", label: "University of California, Santa Cruz" },
  // Ivy League
  { value: "harvard", label: "Harvard University" },
  { value: "yale", label: "Yale University" },
  { value: "princeton", label: "Princeton University" },
  { value: "columbia", label: "Columbia University" },
  { value: "upenn", label: "University of Pennsylvania" },
  { value: "brown", label: "Brown University" },
  { value: "dartmouth", label: "Dartmouth College" },
  // Other top US universities
  { value: "asu", label: "Arizona State University" },
  { value: "auburn", label: "Auburn University" },
  { value: "bu", label: "Boston University" },
  { value: "northeastern", label: "Northeastern University" },
  { value: "case-western", label: "Case Western Reserve University" },
  { value: "clemson", label: "Clemson University" },
  { value: "colorado", label: "University of Colorado Boulder" },
  { value: "duke", label: "Duke University" },
  { value: "drexel", label: "Drexel University" },
  { value: "fsu", label: "Florida State University" },
  { value: "jhu", label: "Johns Hopkins University" },
  { value: "ncsu", label: "North Carolina State University" },
  { value: "nyu", label: "New York University" },
  { value: "psu", label: "Penn State University" },
  { value: "rice", label: "Rice University" },
  { value: "rochester", label: "University of Rochester" },
  { value: "rutgers", label: "Rutgers University" },
  { value: "stevens", label: "Stevens Institute of Technology" },
  { value: "stony-brook", label: "Stony Brook University" },
  { value: "tamu", label: "Texas A&M University" },
  { value: "tufts", label: "Tufts University" },
  { value: "ufl", label: "University of Florida" },
  { value: "uchicago", label: "University of Chicago" },
  { value: "umd", label: "University of Maryland" },
  { value: "umass", label: "University of Massachusetts Amherst" },
  { value: "unc", label: "University of North Carolina at Chapel Hill" },
  { value: "upitt", label: "University of Pittsburgh" },
  { value: "usc", label: "University of Southern California" },
  { value: "utaustin", label: "University of Texas at Austin" },
  { value: "uva", label: "University of Virginia" },
  { value: "uw", label: "University of Washington" },
  { value: "vanderbilt", label: "Vanderbilt University" },
  { value: "vt", label: "Virginia Tech" },
  { value: "wustl", label: "Washington University in St. Louis" },
  { value: "wmu", label: "Western Michigan University" },
  { value: "other", label: "Other" },
];

export const countries = [
  { value: "us", label: "United States" },
  { value: "canada", label: "Canada" },
  { value: "uk", label: "United Kingdom" },
  { value: "mexico", label: "Mexico" },
  { value: "other", label: "Other" },
];

export const degreeOptions = [
  { value: "high-school", label: "High School / Secondary School" },
  { value: "associates", label: "Associate's" },
  { value: "bachelors", label: "Bachelor's" },
  { value: "masters", label: "Master's" },
  { value: "phd", label: "PhD / Doctorate" },
  { value: "other", label: "Other" },
];

export const majorOptions = [
  // Computing
  { value: "cs", label: "Computer Science" },
  { value: "se", label: "Software Engineering" },
  { value: "ce", label: "Computer Engineering" },
  { value: "ai", label: "Artificial Intelligence / Machine Learning" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "datasci", label: "Data Science" },
  { value: "hci", label: "Human-Computer Interaction" },
  { value: "game-design", label: "Game Design / Game Development" },
  { value: "infosci", label: "Information Science / Information Systems" },
  { value: "mis", label: "Management Information Systems" },
  // Engineering
  { value: "ae", label: "Aerospace Engineering" },
  { value: "biomed", label: "Biomedical Engineering" },
  { value: "chem-eng", label: "Chemical Engineering" },
  { value: "civil", label: "Civil Engineering" },
  { value: "ee", label: "Electrical Engineering" },
  { value: "enviro-eng", label: "Environmental Engineering" },
  { value: "ie", label: "Industrial Engineering" },
  { value: "mech", label: "Mechanical Engineering" },
  { value: "nuke", label: "Nuclear Engineering" },
  { value: "robotics", label: "Robotics" },
  { value: "sys-eng", label: "Systems Engineering" },
  // Sciences
  { value: "applied-math", label: "Applied Mathematics" },
  { value: "biochem", label: "Biochemistry" },
  { value: "biology", label: "Biology" },
  { value: "chem", label: "Chemistry" },
  { value: "cog-sci", label: "Cognitive Science" },
  { value: "enviro-sci", label: "Environmental Science" },
  { value: "math", label: "Mathematics" },
  { value: "neuro", label: "Neuroscience" },
  { value: "physics", label: "Physics" },
  { value: "stats", label: "Statistics" },
  // Business / Social
  { value: "accounting", label: "Accounting" },
  { value: "business", label: "Business Administration" },
  { value: "econ", label: "Economics" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "finance", label: "Finance" },
  { value: "marketing", label: "Marketing" },
  // Design / Arts
  { value: "arch", label: "Architecture" },
  { value: "design", label: "Design (Graphic / UX / Product)" },
  { value: "fine-arts", label: "Fine Arts" },
  // Humanities / Other
  { value: "comm", label: "Communications / Media" },
  { value: "education", label: "Education" },
  { value: "linguistics", label: "Linguistics" },
  { value: "polisci", label: "Political Science" },
  { value: "psych", label: "Psychology" },
  { value: "sociology", label: "Sociology" },
  { value: "other", label: "Other or multiple majors" },
];

export const transportationOptions = [
  { value: "driving", label: "Driving" },
  { value: "flying", label: "Flying" },
  { value: "bus", label: "Bus" },
  { value: "train", label: "Train" },
  { value: "local", label: "Local" },
];

export const shirtSizeOptions = [
  { value: "xs", label: "XS" },
  { value: "s", label: "S" },
  { value: "m", label: "M" },
  { value: "l", label: "L" },
  { value: "xl", label: "XL" },
  { value: "xxl", label: "XXL" },
];
