const legacyUniversityNames: Record<string, string> = {
  asu: "Arizona State University",
  auburn: "Auburn University",
  brown: "Brown University",
  bu: "Boston University",
  caltech: "California Institute of Technology",
  "case-western": "Case Western Reserve University",
  clemson: "Clemson University",
  cmu: "Carnegie Mellon University",
  colorado: "University of Colorado Boulder",
  columbia: "Columbia University",
  cornell: "Cornell University",
  dartmouth: "Dartmouth College",
  drexel: "Drexel University",
  duke: "Duke University",
  fsu: "Florida State University",
  gatech: "Georgia Institute of Technology",
  harvard: "Harvard University",
  "iowa-state": "Iowa State University",
  iub: "Indiana University Bloomington",
  jhu: "Johns Hopkins University",
  mit: "Massachusetts Institute of Technology",
  msu: "Michigan State University",
  mtu: "Michigan Technological University",
  ncsu: "North Carolina State University",
  northeastern: "Northeastern University",
  northwestern: "Northwestern University",
  nyu: "New York University",
  osu: "Ohio State University",
  princeton: "Princeton University",
  psu: "Penn State University",
  purdue: "Purdue University",
  rice: "Rice University",
  rochester: "University of Rochester",
  rutgers: "Rutgers University",
  stanford: "Stanford University",
  stevens: "Stevens Institute of Technology",
  "stony-brook": "Stony Brook University",
  tamu: "Texas A&M University",
  tufts: "Tufts University",
  ucberkeley: "University of California, Berkeley",
  ucdavis: "University of California, Davis",
  uci: "University of California, Irvine",
  ucla: "University of California, Los Angeles",
  ucsb: "University of California, Santa Barbara",
  ucsc: "University of California, Santa Cruz",
  ucsd: "University of California, San Diego",
  uchicago: "University of Chicago",
  ufl: "University of Florida",
  uiuc: "University of Illinois Urbana-Champaign",
  umass: "University of Massachusetts Amherst",
  umd: "University of Maryland",
  umich: "University of Michigan - Ann Arbor",
  umn: "University of Minnesota",
  unc: "University of North Carolina at Chapel Hill",
  upenn: "University of Pennsylvania",
  upitt: "University of Pittsburgh",
  usc: "University of Southern California",
  utaustin: "University of Texas at Austin",
  uva: "University of Virginia",
  uw: "University of Washington",
  vanderbilt: "Vanderbilt University",
  vt: "Virginia Tech",
  wisc: "University of Wisconsin-Madison",
  wmu: "Western Michigan University",
  wustl: "Washington University in St. Louis",
  yale: "Yale University",
};

export function normalizeLegacyUniversity(value: unknown) {
  if (typeof value !== "string") return "";
  return legacyUniversityNames[value] ?? value;
}
