import type { Ref } from "react";
import type { TicketState } from "@/lib/pass/types";
import { formatDef, ticketScale, ticketSize } from "@/lib/pass/formats";
import { backdropDef } from "@/lib/pass/backdrops";
import { ticketTheme } from "@/lib/pass/themes";
import { useCrossfade, useThemeTransition } from "@/lib/pass/motion";
import { useMagneticTilt } from "@/lib/pass/use-magnetic-tilt";
import { Ticket } from "@/components/pass/ticket";

/*
  The share frame — the thing that actually gets exported.

  ── The one thing to understand first ──

  The preview and the export are the same DOM node. This is laid out at the
  format's true pixel size (1080×1920, 1080×1080 or 1200×628) and only
  transform-scaled down to fit its column; downloading rasterizes this exact
  element at pixelRatio 1, so the PNG lands on the dimensions by construction
  and can never drift from what was on screen.

  Three constraints follow from that, and breaking any of them only shows up in
  the exported PNG — never in the preview:

  - No `clip-path: url(#id)`, no <pattern> refs, no external assets anywhere on
    the pass. None of them survive html-to-image's clone-into-<foreignObject>
    step. The ticket silhouette — rounded corners plus the two notches at the
    perforation — is one inline `clip-path: path()` in lib/pass/geometry.ts,
    and the paper glitter is a URI-encoded inline SVG rather than a blend mode.
  - Backdrops and marks stay plain same-origin /public URLs. next/image hands
    back a <picture> and a srcset of /_next/image URLs that html-to-image
    cannot resolve; the picker thumbnails in controls.tsx are the one place
    next/image is used, because that subtree is never rasterized.
  - Fonts must be registered in `document.fonts` before capture. lib/pass/
    share.ts reads the faces the frame actually computed to and awaits exactly
    those — the family names are generated by next/font, so they cannot be
    hardcoded.

  ── The GSAP trap ──

  GSAP writes the whole `transform` property. Several elements here already
  carry a layout transform (the fit-to-column scale, the ticket's own scale),
  and a tween targeting the same node silently wipes it — the frame then
  renders at full size. Every animated element therefore gets its own wrapper,
  separate from the node holding the layout transform. That is why the tilt,
  the format flip and the fit scale are three nested divs rather than one.
*/

type Props = {
  state: TicketState;
  frameRef?: Ref<HTMLDivElement>;
  /** Preview only. Off during capture so a leaning pass never exports leaning. */
  interactive?: boolean;
  /**
   * Whether a backdrop change dissolves in place. False on the landing reel,
   * where the whole card is swapped behind a slide and an in-place dissolve
   * would land the incoming pass on the outgoing backdrop.
   */
  animateBackdrop?: boolean;
};

const LAYER = {
  position: "absolute",
  inset: 0,
  width: "100%",
  height: "100%",
  objectFit: "cover" as const,
  objectPosition: "center",
} as const;

export function ExportFrame({
  state,
  frameRef,
  interactive = false,
  animateBackdrop = true,
}: Props) {
  const format = formatDef(state.format);
  const { w, h } = ticketSize(format);
  const scale = ticketScale(format);

  // The frame is the catch area, so the pass leans toward the pointer as it
  // crosses the backdrop rather than only once it is over the card.
  const tiltRef = useMagneticTilt(interactive);

  const theme = ticketTheme(state.backdrop);
  // The backdrop dissolves and the pass's ink tweens across the same beat, so
  // switching backdrop reads as one change rather than three.
  const { under: backdropUnder, topRef: backdropRef } =
    useCrossfade<HTMLImageElement>(
      backdropDef(state.backdrop).src,
      0.6,
      animateBackdrop,
    );
  const themeRef = useThemeTransition(theme.vars, 0.6, animateBackdrop);

  return (
    <div
      ref={frameRef}
      className="relative flex items-center justify-center overflow-hidden"
      style={{
        width: format.width,
        height: format.height,
        backgroundColor: "var(--ui-surface)",
      }}
    >
      {/* Plain /public URLs, not next/image: html-to-image has to fetch these
          and inline them as data URLs, and the optimizer's srcset of
          /_next/image?url=… is not something it can resolve. */}
      {backdropUnder ? (
        <img aria-hidden src={backdropUnder} alt="" style={LAYER} />
      ) : null}
      <img
        aria-hidden
        ref={backdropRef}
        src={backdropDef(state.backdrop).src}
        alt=""
        fetchPriority="high"
        style={LAYER}
      />

      <div
        ref={tiltRef}
        className="mh-tilt"
        style={{
          position: "relative",
          width: w * scale,
          height: h * scale,
        }}
      >
        <div
          ref={themeRef}
          style={{
            width: w,
            height: h,
            transform: `scale(${scale})`,
            transformOrigin: "top left",
            // drop-shadow rather than box-shadow: it follows the clipped
            // silhouette, so the notches cast a shadow too.
            filter: `drop-shadow(0 22px 44px ${theme.shadow})`,
            transition: animateBackdrop
              ? "filter 600ms var(--mh-ease)"
              : "none",
          }}
        >
          <Ticket state={state} />
        </div>
      </div>
    </div>
  );
}
