import "server-only";

import { readFile } from "node:fs/promises";
import path from "node:path";

import { PKPass } from "passkit-generator";

import { getWalletConfig } from "@/lib/wallet/config";
import { WALLET_EVENT } from "@/lib/wallet/event";

/**
 * Generated by scripts/generate-wallet-assets.ts. They live under public/ so
 * the standalone build's `cp -r public` ships them without any file tracing
 * configuration; they are only logos, so being publicly served costs nothing.
 */
const IMAGE_FILES = [
  "icon.png",
  "icon@2x.png",
  "icon@3x.png",
  "logo.png",
  "logo@2x.png",
  "strip.png",
  "strip@2x.png",
  "strip@3x.png",
] as const;

let imageBuffers: Promise<Record<string, Buffer>> | null = null;

function loadImages() {
  imageBuffers ??= (async () => {
    const dir = path.join(process.cwd(), "public/wallet/pass");
    const entries = await Promise.all(
      IMAGE_FILES.map(
        async (file) => [file, await readFile(path.join(dir, file))] as const,
      ),
    );
    return Object.fromEntries(entries);
  })().catch((error) => {
    // Don't cache a failed read; the next request retries.
    imageBuffers = null;
    throw error;
  });
  return imageBuffers;
}

/**
 * Builds a signed .pkpass whose QR code is exactly the dashboard check-in
 * code: the bare user id. The scanner and checkInAttendee() therefore accept
 * it without knowing Wallet exists.
 */
export async function buildCheckInPass({
  userId,
  firstName,
  lastName,
  origin,
}: {
  userId: string;
  firstName: string;
  lastName: string;
  origin: string;
}): Promise<Buffer> {
  const config = getWalletConfig();
  const attendee = [firstName.trim(), lastName.trim()]
    .filter(Boolean)
    .join(" ");

  const passJson = {
    formatVersion: 1,
    passTypeIdentifier: config.passTypeIdentifier,
    teamIdentifier: config.teamIdentifier,
    // One pass per account: re-downloading replaces the pass in Wallet
    // instead of stacking a second copy beside it.
    serialNumber: userId,
    organizationName: "MHacks",
    description: `${WALLET_EVENT.name} check-in pass`,
    // The sky ticket theme in lib/pass/themes.ts, on its paper stock.
    backgroundColor: "rgb(240, 247, 250)",
    foregroundColor: "rgb(20, 58, 74)",
    labelColor: "rgb(74, 125, 146)",
    // Advisory only — Wallet hides the share button, nothing more.
    sharingProhibited: true,
    // Pre-iOS 18 devices ignore relevantDates and read this instead.
    relevantDate: WALLET_EVENT.relevantIntervals[0].startDate,
    logoText: WALLET_EVENT.name,
    eventTicket: {
      // No primary field: it would be drawn over the sky strip in the navy
      // foreground colour and barely read. Everything sits below the strip.
      secondaryFields: [
        { key: "attendee", label: "HACKER", value: attendee || "Hacker" },
      ],
      auxiliaryFields: [
        { key: "dates", label: "DATES", value: WALLET_EVENT.dates },
        { key: "city", label: "WHERE", value: "Ann Arbor, MI" },
      ],
      backFields: [
        {
          key: "how",
          label: "Checking in",
          value:
            "Show this QR code to event staff at registration, meals and events. Turn your brightness up if it won't scan.",
        },
        { key: "venue", label: "Venue", value: WALLET_EVENT.venue },
        {
          key: "dashboard",
          label: "Dashboard",
          value: `${origin}/dashboard`,
        },
        {
          key: "fallback",
          label: "Can't open this pass?",
          value: `Your code is also at ${origin}/dashboard/qr`,
        },
        {
          key: "support",
          label: "Questions",
          value: WALLET_EVENT.supportEmail,
        },
      ],
    },
  };

  const pass = new PKPass(
    {
      ...(await loadImages()),
      "pass.json": Buffer.from(JSON.stringify(passJson)),
    },
    config.certificates,
  );

  pass.setBarcodes({
    format: "PKBarcodeFormatQR",
    message: userId,
    messageEncoding: "iso-8859-1",
  });
  pass.setRelevantDates(
    WALLET_EVENT.relevantIntervals.map((interval) => ({ ...interval })),
  );
  pass.setLocations({
    ...WALLET_EVENT.location,
    relevantText: `Welcome to ${WALLET_EVENT.name}`,
  });
  pass.setExpirationDate(new Date(WALLET_EVENT.endsAt));

  return pass.getAsBuffer();
}
