import "server-only";

import { readFile } from "node:fs/promises";
import path from "node:path";

import { PKPass } from "passkit-generator";

import { getAppleWalletConfig } from "@/lib/wallet/config";
import {
  WALLET_EVENT,
  WALLET_PASS_COPY,
  walletFallbackText,
} from "@/lib/wallet/event";

/**
 * Generated by scripts/generate-wallet-assets.ts. They live under public/ so
 * the standalone build's `cp -r public` ships them without any file tracing
 * configuration; they are only logos, so being publicly served costs nothing.
 */
const IMAGE_FILES = [
  "icon.png",
  "icon@2x.png",
  "icon@3x.png",
  "logo.png",
  "logo@2x.png",
  "logo@3x.png",
  "thumbnail.png",
  "thumbnail@2x.png",
  "thumbnail@3x.png",
  "background.png",
  "background@2x.png",
  "background@3x.png",
] as const;

let imageBuffers: Promise<Record<string, Buffer>> | null = null;

function loadImages() {
  imageBuffers ??= (async () => {
    const dir = path.join(process.cwd(), "public/wallet/pass");
    const entries = await Promise.all(
      IMAGE_FILES.map(
        async (file) => [file, await readFile(path.join(dir, file))] as const,
      ),
    );
    return Object.fromEntries(entries);
  })().catch((error) => {
    // Don't cache a failed read; the next request retries.
    imageBuffers = null;
    throw error;
  });
  return imageBuffers;
}

/**
 * Builds a signed .pkpass whose QR code is exactly the dashboard check-in
 * code: the bare user id. The scanner and checkInAttendee() therefore accept
 * it without knowing Wallet exists.
 */
export async function buildCheckInPass({
  userId,
  firstName,
  lastName,
  origin,
}: {
  userId: string;
  firstName: string;
  lastName: string;
  origin: string;
}): Promise<Buffer> {
  const config = getAppleWalletConfig();
  const attendee = [firstName.trim(), lastName.trim()]
    .filter(Boolean)
    .join(" ");

  const passJson = {
    formatVersion: 1,
    passTypeIdentifier: config.passTypeIdentifier,
    teamIdentifier: config.teamIdentifier,
    // One pass per account: re-downloading replaces the pass in Wallet
    // instead of stacking a second copy beside it.
    serialNumber: userId,
    organizationName: "MHacks",
    description: `${WALLET_EVENT.name} Ticket`,
    // The "MHacks Check In" Pass Designer template. The colour shows while
    // the blurred background image loads and wherever Wallet can't draw it.
    backgroundColor: "rgb(56, 108, 54)",
    foregroundColor: "rgb(255, 255, 255)",
    labelColor: "rgb(254, 255, 255)",
    // Advisory only — Wallet hides the share button, nothing more.
    sharingProhibited: true,
    // Pre-iOS 18 devices ignore relevantDates and read this instead.
    relevantDate: WALLET_EVENT.relevantIntervals[0].startDate,
    logoText: "MHacks",
    eventTicket: {
      primaryFields: [{ key: "dates", ...WALLET_PASS_COPY.date }],
      secondaryFields: [
        {
          key: "attendee",
          label: WALLET_PASS_COPY.attendee.label,
          value: attendee || WALLET_PASS_COPY.attendee.fallback,
        },
      ],
      backFields: [
        {
          key: "how",
          ...WALLET_PASS_COPY.checkingIn,
        },
        { key: "venue", ...WALLET_PASS_COPY.venue },
        {
          key: "handbook",
          ...WALLET_PASS_COPY.handbook,
        },
        {
          key: "website",
          ...WALLET_PASS_COPY.website,
        },
        {
          key: "fallback",
          label: WALLET_PASS_COPY.fallbackLabel,
          value: walletFallbackText(origin),
        },
        {
          key: "support",
          ...WALLET_PASS_COPY.support,
        },
      ],
    },
  };

  const pass = new PKPass(
    {
      ...(await loadImages()),
      "pass.json": Buffer.from(JSON.stringify(passJson)),
    },
    config.certificates,
  );

  pass.setBarcodes({
    format: "PKBarcodeFormatQR",
    message: userId,
    messageEncoding: "iso-8859-1",
  });
  pass.setRelevantDates(
    WALLET_EVENT.relevantIntervals.map((interval) => ({ ...interval })),
  );
  pass.setLocations({
    ...WALLET_EVENT.location,
    relevantText: `Welcome to ${WALLET_EVENT.name}`,
  });
  // iOS 27+ shows this as a button on the front; the back field above covers
  // older devices.
  pass.featuredActions = [
    {
      identifier: "Handbook",
      type: "viewSchedule",
      url: WALLET_EVENT.handbookUrl,
    },
  ];
  pass.setExpirationDate(new Date(WALLET_EVENT.endsAt));

  return pass.getAsBuffer();
}
