name: CD

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  CONTAINER_NAME: ${{ github.event.repository.name }}
  ECS_CLUSTER: mhacks-ecs
  ECS_SERVICE: mhacks-${{ github.event.repository.name }}
  ECS_TASK_DEFINITION: mhacks-${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/mhacks-github
          aws-region: us-east-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.CONTAINER_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: ./Dockerfile

      - name: Push image to ECR
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ steps.login-ecr.outputs.registry }}

      - name: Substitute account ID in task definition
        run: sed -i "s/AWS_ACCOUNT_ID/${{ secrets.AWS_ACCOUNT_ID }}/g" task-definition.json

      - name: Render task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.push.outputs.registry-path }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        timeout-minutes: 5
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
